### PR TITLE
Add support for sourcemaps given as data urls

### LINKED ISSUE #127: Handle data: url sourcemaps
I'm using indium with jest, which transforms files on the fly and sets sourcemap urls as base64 encoded data. Here's an example: `data:application/json;charset=utf-8;base64,eyJ2...`

As you can imagine, these are extremely long "urls", which I think indium tries to resolve to a file. Emacs complains somewhere with the following error:

> **file-error** *Opening input file* File name too long /path/to/original/file's/dir/data:application/json;charset=utf-8;base64,eyJ2Z...`

`websocket-default-error-handler` displays a warning for this and then indium is left in an inconsistent state. 

I'd be happy to submit a PR for this, but I can't figure out where exactly the file is attempted to be opened. (Since the callback is asynchronous I can't just the debugger) If you give me a couple of pointers, I'll take a crack at it

### PR DESCRIPTION
**Pull request by felipeochoa**
Closes #127

### CODE REVIEW

**Comment by NicolasPetton** [comment]
Thank you! That feature was really missing, it's awesome.
I'll test it locally on Monday and merge it. 

If you want, you can also remove the note in the documentation: https://indium.readthedocs.io/en/latest/debugger.html?highlight=sourcemap#using-sourcemaps

- remove the note from the file in `sphinx-doc/`
- run `make html` and `make-info` from `sphinx-doc`

**Comment by felipeochoa** [comment]
Thanks! So just to be clear, inline sourcemaps == data url sourcemaps? If so, I'll update the docs and push a new version

**Comment by NicolasPetton** [comment]
Yes, that's exactly it.

**Comment by NicolasPetton** [comment]
Thanks again for the PR, merging it!

**Pull request merged**
