### PR TITLE
Add support for storing previously used workspace directories

### LINKED ISSUE #65: Indium should propose existing workspaces when it can't find one
Sometimes I do `M-x indium-connect-to-chrome` from a directory outside of the JS project. This is annoying because the debugger won't find my local files. It would be great if `indium-connect-to-chrome` could ask for a known workspace to bind to if it can't find any where `indium-connect-to-chrome` is started. That could for example be implemented with a `defcustom` remembering workspaces.

### PR DESCRIPTION
**Pull request by NicolasPetton**
Fix #65.

* Store workspace directories in a file
* Prompt the user for a workspace to choose from no workspace can be found from
  the default-directory.

### CODE REVIEW

**Comment by TatriX** [comment]
Can simply
```lisp
(setq indium-workspaces '("/path/to/workspace"))
```
in my `.emacs`?

**Comment by NicolasPetton** [comment]
@TatriX it's a list built as you open connections. Would you like the file storing it to be optional?

**Comment by TatriX** [comment]
Yes I'd like to have a simple option in my `.emacs`.

**Comment by NicolasPetton** [comment]
@TatriX now you can do it, see 2389c05

**Comment by TatriX** [comment]
Awesome!

**Pull request merged**
