### PR TITLE
Add interactive operation for indium-connect-to-chrome

### PR DESCRIPTION
**Pull request by ebpa**
Implements enhancement described in #134

### CODE REVIEW

**Comment by ebpa** [comment]
It's a minor change, so easy to rebase when you're ready for it!  :+1:

@NicolasPetton, it looks like all branches that have been pushed to the repo have been merged with master.  Could you delete them?  I was just checking to see if you had pushed your WIP refactoring branch.

If you're open to collaboration on the refactor I'd love to help :-)

**Comment by diasbruno** [comment]
Looks good. You can close #146 in favour of this one.  👍

**Comment by NicolasPetton** [comment]
Erik Anderson <notifications@github.com> writes:

> It's a minor change, so easy to rebase when you're ready for it!  :+1:

Cool, thanks.

> @NicolasPetton, it looks like all branches that have been pushed to
> the repo have been merged with master.  Could you delete them?  I was
> just checking to see if you had pushed your WIP refactoring branch.

The branch is "workspaces".

I'm still trying to figure out the best way to do this, so you'll only
see temp commits in there, but I'll rewrite the history later.

The idea is to use a .indium.json file similar to VSCode to be able to
configure Indium per project.

This will enable better support for sourcemaps with project-specific
sourcemap path and resolution settings, and improve other things like
nodejs connection setups.

Another bonus is the ability to configure indium once and put the
configuration under version control within a project.

> If you're open to collaboration on the refactor I'd love to help :-)

I'm definitely open to collaboration.  I'll try to rewrite the history
and fix unit tests this weekend and I'll ping you right after that.

You can have a look at indium-workspace.el to get an idea of the current
state of the branch.

The next step afer fixing the tests will be to improve sourcemap support
with configurations like:

    {
        "name": "Chrome React project",
        "type": "chrome",
        "url": "http://localhost:3000",
        "webRoot": "./src",
        "sourceMaps": true,
        "sourceMapPathOverrides": {
            "webpack:///./~/*": "${webRoot}/node_modules/*",       // Example: "webpack:///./~/querystring/index.js" -> "/Users/me/project/node_modules/querystring/index.js"
            "webpack:///./*":   "${webRoot}/*",                    // Example: "webpack:///./src/app.js" -> "/Users/me/project/src/app.js",
            "webpack:///*":     "*",                               // Example: "webpack:///project/app.ts" -> "/project/app.ts"
            "webpack:///src/*": "${webRoot}/*"
        }
    }

**Comment by NicolasPetton** [comment]
@ebpa I rewrote the history and pushed a few more changes.

The next steps IMO are:
- Fix all unit tests (I fixed some already)
- Finish the update of the documentation
- Add support for sourcemap path overrides

Tell me if you want to work on this branch!

Thanks!

**Comment by ebpa** [comment]
I would!

I was having trouble running tests locally via the make targets (`make ci-dependencies` then `make test`?), but adding a Cask file let me install dependencies using `cask install` and then run the tests with `cask exec buttercup -L .`.

When I run tests using this approach I see:

    Ran 164 specs, 42 failed, in 15.0 seconds.

Is that consistent with the testing in your environment for the workspaces branch (b5602ad)?

**Comment by NicolasPetton** [comment]
Erik Anderson <notifications@github.com> writes:

> I was having trouble running tests locally via the make targets (`make
> ci-dependencies` then `make test`?), but adding a Cask file let me
> install dependencies using `cask install` and then run the tests with
> `cask exec buttercup -L .`.
>
> When I run tests using this approach I see:
>
>     Ran 164 specs, 42 failed, in 15.0 seconds.
>
> Is that consistent with the testing in your environment for the
> workspaces branch (b5602ad)?

Yes, it is.

**Comment by NicolasPetton** [comment]
@ebpa The workspace and sourcemaps refactoring has been merged in master.
The updated doc is here: https://indium.readthedocs.io/en/latest/setup.html

**Comment by NicolasPetton** [comment]
@ebpa I'm closing this PR as it has been stalled for quite some time now.
If you want, you can still update & rebase your branch and reopen it, I'd definitely review it!

Thanks!

**Pull request closed without merging**
