### PR TITLE
Extract part of indium-client.el into a new library.

### PR DESCRIPTION
**Pull request by DamienCassou**
This commit extracts part of indium-client.el into a reusable library (that I would like to use for a basecamp integration): [json-process-client.el](https://github.com/NicolasPetton/Indium/files/3365484/json-process-client.txt). If you agree with this extraction, I can take care of creating a repo (under `DamienCassou/`) or you can do it yourself (which would make more sense because you are the author). I will take care of creating a PR for MELPA unless you want to do it yourself.

* indium-client.el:
(indium-client--connection)
(indium-client--process)
(indium-client--callbacks): Remove to have `indium-client--application`
instead.
(indium-client--application): New variable to save the return value of
`json-process-client-start`.
(indium-client-start): Rewrite to call `json-process-client-start`.
(indium-client-stop): Rewrite to call `json-process-client-stop`.
(indium-client-send): Rewrite to call `json-process-client-send`.
(indium-client-process-live-p): Rewrite to call
`json-process-client-process-live-p`.
(indium-client--ensure-process)
(indium-client--start-server)
(indium-client--process-filter-function)
(indium-client--open-network-stream)
(indium-client--connection-sentinel)
(indium-client--connection-filter)
(indium-client--handle-data)
(indium-client--complete-message-p): Move to the new
`json-process-client` library.
(indium-client--handle-message): Add CALLBACK parameter.
(indium-client--handle-response): Call the CALLBACK parameter instead
of getting it from a global variable.

### CODE REVIEW

**Comment by DamienCassou** [comment]
I will also migrate the unit tests if you agree with the extraction.

**Comment by DamienCassou** [comment]
ping

**Comment by DamienCassou** [comment]
[json-process-client](https://stable.melpa.org/#/json-process-client) in on melpa now. This is ready to be merged in my opinion. One hundred and fourty lines less of code in Indium :-).

**Comment by DamienCassou** [comment]
ping

**Comment by NicolasPetton** [comment]
MergedA

**Pull request merged**
